kind: pipeline
name: default
type: docker

steps:
  - name: test script
    image: curlimages/curl
    commands: 
    - export PLUGIN_CITY=BFS
    - sh script.sh
    
  - name: git-leak
    image: plugins/gitleaks
    pull: if-not-exists

  - name: scan
    image: plugins/drone-snyk
    privileged: true
    settings:
      image: drone_playground/hello-world
      debug: true
      username:
        from_secret: username
      password:
        from_secret: password
      snyk:
        from_secret: snyk
      fail_on_issues: false

  - name: publish
    image: plugins/docker
    settings:
      repo: plugins/drone_playground
      auto_tag: true
      username:
        from_secret: username
      password:
        from_secret: password

